// Re-exports from openaiAssistants (shared for now — will be replaced with
// Responses-native adapters as the new surface is built)
export { supercompat as createClient } from '../openaiAssistants/supercompat'
export { supercompat } from '../openaiAssistants/supercompat'
export { groqClientAdapter } from '../openaiAssistants/adapters/client/groqClientAdapter'
export { openaiClientAdapter } from '../openaiAssistants/adapters/client/openaiClientAdapter'
export { azureOpenaiClientAdapter } from '../openaiAssistants/adapters/client/azureOpenaiClientAdapter'
export { azureAiProjectClientAdapter } from '../openaiAssistants/adapters/client/azureAiProjectClientAdapter'
export { mistralClientAdapter } from '../openaiAssistants/adapters/client/mistralClientAdapter'
export { perplexityClientAdapter } from '../openaiAssistants/adapters/client/perplexityClientAdapter'
export { anthropicClientAdapter } from '../openaiAssistants/adapters/client/anthropicClientAdapter'
export { togetherClientAdapter } from '../openaiAssistants/adapters/client/togetherClientAdapter'
export { googleClientAdapter } from '../openaiAssistants/adapters/client/googleClientAdapter'
export { humirisClientAdapter } from '../openaiAssistants/adapters/client/humirisClientAdapter'
export { ollamaClientAdapter } from '../openaiAssistants/adapters/client/ollamaClientAdapter'
export { openRouterClientAdapter } from '../openaiAssistants/adapters/client/openRouterClientAdapter'
export { completionsRunAdapter } from '../openaiAssistants/adapters/run/completionsRunAdapter'
export { prismaStorageAdapter } from './prismaStorageAdapter'
export { responsesPassthroughRunAdapter } from './adapters/run/responsesPassthroughRunAdapter'
export { anthropicRunAdapter } from './adapters/run/anthropicRunAdapter'
export { azureAgentsResponsesRunAdapter } from './adapters/run/azureAgentsRunAdapter'
export { geminiRunAdapter } from './adapters/run/geminiRunAdapter'
